version: '3.9'
services:
  "{{project_artifact_id}}":
    image: {{project_artifact_id}}
    container_name: {{project_artifact_id}}
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: default
    ports:
      - ${APP_INGRESS_SERVER_PORT:-8080}:8080
    build: .
    healthcheck:
      test: curl http://localhost:8080
      interval: 5s
      retries: 10
      start_period: 5s
      timeout: 10s
    networks:
      - app-{{project_artifact_id}}
networks:
  app-{{project_artifact_id}}:
    driver: bridge

