kind: plugin
schema-version: v1
spec:
  about: docs/about.md
  requirements: docs/requirements.md
  implementation: docs/implementation.md
  type: app
  release-notes: docs/release-notes-0.0.1.md
  usage: docs/usage.md
  technologies:
    - .NET
    - C#
  compatibility:
    - net6.0

  repository: https://github.com/stack-spot/growth-example-plugins/dotnet-errorhandler-plugin
  computed-inputs:
    file: "Program.cs"
    base_path: "{% if global_computed_inputs.src_base_path is defined and global_computed_inputs.src_base_path != '' %}{{global_computed_inputs.src_base_path}}{% else %}{{'.'}}{% endif %}"

  hooks:
#package
  - type: run
    trigger: before-render
    commands:
    - dotnet add {{computed_inputs.base_path}}/src/{{global_inputs.project_name}}.Application package StackSpot.ErrorHandler
    - dotnet add {{computed_inputs.base_path}}/src/{{global_inputs.project_name}}.Infrastructure package StackSpot.ErrorHandler
#dependencyinjection
  - type: edit
    trigger: before-render
    path: "{{computed_inputs.base_path}}/src/{{project_name}}.Api/{{computed_inputs.file}}"
    changes:
    - search:
        string: "using"
        insert-before:
          value: "using StackSpot.ErrorHandler;"
        when:
          not-exists: "using StackSpot.ErrorHandler;"
    - search:
        string: "app.UseRouting()"
        insert-before:
          value: "app.UseErrorHandler();\n"
        when:
          not-exists: "app.UseErrorHandler();"
#format
  - type: run
    trigger: after-render
    working-dir: "{{computed_inputs.base_path}}/src/{{project_name}}.Api"
    commands:
    - dotnet dotnet-format --include-generated

metadata:
  picture: plugin.png
  display-name: .NET Error Handler
  version: 0.0.1
  name: dotnet-errorhandler-plugin
  description: Plugin to standardize error returns from REST applications.