schema-version: v2
kind: action
metadata:
  name: create-github-repo
  display-name: Create Github Repository
  description: Action to create a repository on GitHub using GitHub's API.
  version: 0.0.2
  picture: action.png
spec:
  type: python
  about: docs/about.md
  usage: docs/usage.md
  release-notes: docs/release-notes.md
  requirements: docs/requirements.md
  implementation: docs/implementation.md
  repository: https://github.com/stack-spot/growth-demo-plugins/create-repo-github-action
  inputs:
      - label: Visibility
        name: visibility
        type: text
        required: true
        items: 
          - public
          - internal
          - private
  python:
    workdir: .
    script: script.py
