schema-version: v2
kind: plugin
metadata:
  name: dotnet-api-plugin
  display-name: .NET API 
  description: Base template for developing a complete API using C# and REST, running in a container cluster
  version: 0.0.4
  picture: plugin.png
spec:
  type: app
  compatibility:
    - net6.0
  about: docs/about.md
  usage: docs/usage.md
  implementation: docs/implementation.md
  #requirements: docs/requirements.md
  repository: https://github.com/stack-spot/growth-demo-plugins
  release-notes: docs/release-notes-0.0.1.md
  technologies:
    - .NET
    - C#
    - Api
  inputs:
    - label: Project name
      type: text
      name: project_name
      global: true
      required: true
      pattern: '(^[a-zA-Z_\d\.]*$)'  
  global-computed-inputs:
    project_type: "Api"
    src_base_path: ""
    framework: "net6.0"
    project_name_kebabcase: "{{project_name | kebabcase | replace('.','')}}"
  hooks:
  #package / apply template / install dotnet-format
    - type: run
      trigger: after-render
      commands:
        - dotnet new tool-manifest --force
        - dotnet tool install --local dotnet-format